version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sb-ecom-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: sbecom
      RABBITMQ_DEFAULT_PASS: sbecom@001!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailpit:
    image: axllent/mailpit:latest
    container_name: sb-ecom-mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI at http://localhost:8025
    restart: unless-stopped

volumes:
  rabbitmq_data:
